### ISSUE TITLE
Your way of colorizing text

### ISSUE THREAD

**Issue by Sxtanna** [MTM123/FactionsAddons#1]
You use 
```java
replace('&', ChatColor.COLOR_CHAR)
```
in a couple of places.

I would consider this a bad habit, is there any reason you don't simply use the ChatColor Enum?

**Comment by MTM123** [comment]
Some time back I actually talked about this issue with @RubbaBoy and also learned that ChatColor#translateAlternateColorCodes() method functionality is different from String#replace()
 
I will use ChatColor#translateAlternateColorCodes() from now on
